ACTIVITY_PHRASES = {
    "en": (
        "Turning the next page",
        "Keeping chapters in order",
        "The commas are behaving",
        "Following the author’s voice",
        "Preparing the next passage",
        "Working through the text",
        "Aligning the margins",
        "Checking the chapter rhythm",
        "Keeping the voice on the page",
        "Warming up the next paragraph",
        "Untangling a long sentence",
        "Letting the semicolons breathe",
        "Carrying meaning across",
        "Dusting off the footnotes",
        "Keeping the links in place",
        "Folding the page corner gently",
        "Reading between the lines",
        "Sharpening the phrasing",
        "Threading one paragraph to the next",
        "Saving the author’s cadence",
        "Making the glossary behave",
        "Checking the quiet details",
        "Preparing a cleaner page",
        "Holding the structure steady",
    ),
    "ru": (
        "Переворачиваю следующую страницу",
        "Главы остаются на своих местах",
        "Запятые ведут себя прилично",
        "Бережно веду голос автора",
        "Готовлю следующий фрагмент",
        "Перевожу текст",
        "Выравниваю поля",
        "Проверяю ритм главы",
        "Держу голос автора на странице",
        "Разогреваю следующий абзац",
        "Распутываю длинное предложение",
        "Даю точкам с запятой подышать",
        "Переношу смысл через языки",
        "Сдуваю пыль со сносок",
        "Сохраняю ссылки на местах",
        "Аккуратно загибаю уголок страницы",
        "Читаю между строк",
        "Оттачиваю формулировку",
        "Сшиваю абзацы между собой",
        "Берегу авторский ритм",
        "Уговариваю глоссарий вести себя прилично",
        "Проверяю тихие детали",
        "Готовлю чистую страницу",
        "Держу структуру ровно",
    ),
    "uk": (
        "Гортаю наступну сторінку",
        "Розділи тримаються купи",
        "Коми поводяться чемно",
        "Бережу голос автора",
        "Готую наступний фрагмент",
        "Перекладаю текст",
        "Вирівнюю поля",
        "Перевіряю ритм розділу",
        "Тримаю голос автора на сторінці",
        "Розігріваю наступний абзац",
        "Розплутую довге речення",
        "Даю крапкам з комою подихати",
        "Переношу сенс між мовами",
        "Здуваю пил зі зносок",
        "Тримаю посилання на місці",
        "Обережно загинаю кутик сторінки",
        "Читаю між рядками",
        "Відточую формулювання",
        "Зшиваю абзаци між собою",
        "Бережу авторський ритм",
        "Прошу глосарій поводитися чемно",
        "Перевіряю тихі деталі",
        "Готую чисту сторінку",
        "Тримаю структуру рівно",
    ),
    "fr": (
        "Je tourne la page suivante",
        "Les chapitres restent en ordre",
        "Les virgules se tiennent bien",
        "Je garde le ton de l’auteur",
        "Je prépare le prochain passage",
        "Travail sur le texte",
        "J’aligne les marges",
        "Je vérifie le rythme du chapitre",
        "Je garde la voix sur la page",
        "Je prépare le prochain paragraphe",
        "Je démêle une longue phrase",
        "Je laisse respirer les points-virgules",
        "Je fais passer le sens",
        "J’époussette les notes de bas de page",
        "Je garde les liens en place",
        "Je corne doucement la page",
        "Je lis entre les lignes",
        "J’affine la formulation",
        "Je relie les paragraphes",
        "Je préserve la cadence de l’auteur",
        "Je rappelle le glossaire à l’ordre",
        "Je vérifie les détails discrets",
        "Je prépare une page plus nette",
        "Je maintiens la structure",
    ),
    "es": (
        "Pasando la siguiente página",
        "Los capítulos siguen en orden",
        "Las comas se portan bien",
        "Cuidando la voz del autor",
        "Preparando el siguiente pasaje",
        "Trabajando el texto",
        "Alineando los márgenes",
        "Revisando el ritmo del capítulo",
        "Manteniendo la voz en la página",
        "Preparando el siguiente párrafo",
        "Desenredando una frase larga",
        "Dejando respirar los puntos y coma",
        "Llevando el sentido de un idioma a otro",
        "Sacudiendo el polvo de las notas",
        "Manteniendo los enlaces en su sitio",
        "Doblando con cuidado la esquina de la página",
        "Leyendo entre líneas",
        "Afinando la frase",
        "Hilando un párrafo con el siguiente",
        "Cuidando la cadencia del autor",
        "Convenciendo al glosario de portarse bien",
        "Revisando los detalles silenciosos",
        "Preparando una página más limpia",
        "Sosteniendo la estructura",
    ),
    "nl": (
        "De volgende bladzijde draait",
        "De hoofdstukken blijven op volgorde",
        "De komma’s gedragen zich",
        "De stem van de auteur blijft dichtbij",
        "De volgende passage wordt voorbereid",
        "Aan de tekst werken",
        "De marges rechtzetten",
        "Het ritme van het hoofdstuk controleren",
        "De stem op de pagina houden",
        "De volgende alinea klaarmaken",
        "Een lange zin ontwarren",
        "De puntkomma’s laten ademen",
        "Betekenis naar de overkant brengen",
        "Het stof van de voetnoten halen",
        "De links op hun plek houden",
        "Het hoekje van de pagina voorzichtig vouwen",
        "Tussen de regels lezen",
        "De formulering aanscherpen",
        "Alinea’s aan elkaar rijgen",
        "De cadans van de auteur bewaren",
        "Het glossarium tot de orde roepen",
        "De stille details controleren",
        "Een schonere pagina voorbereiden",
        "De structuur stevig vasthouden",
    ),
}


def get_activity_phrases(interface_language: str = "en") -> tuple[str, ...]:
    return ACTIVITY_PHRASES.get(interface_language, ACTIVITY_PHRASES["en"])
